
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cocon_development
  username: postgres
  password: omniood

  
test:
  <<: *default
  database: cocon_test
  username: postgres
  password: omniood


production:
  <<: *default
  database: cocon_production
  username: rms
  password: <%= ENV['RMS_DATABASE_PASSWORD'] %>
